import {build} from 'esbuild';
import {expect,test} from '@playwright/test';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
// @ts-expect-error Checked build helper has no declaration file.
import {mermaidMathPlugin} from '../../scripts/mermaid-build.mjs';

const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
const plain='sankey\nAlpha,Beta,3\nBeta,Gamma,2\nAlpha,Gamma,1\n';
const math=String.raw`sankey
"left $$\frac{a}{b}$$","middle $$x$$",3
"left $$\frac{a}{b}$$","right $$\begin{matrix}a&b\\c&d\end{matrix}$$",2
"$$\rlap{\rule{6em}{1em}}z$$","right $$\begin{matrix}a&b\\c&d\end{matrix}$$",1
`;
let bundle:string,upstream:string;
test.beforeAll(async()=>{const options={bundle:true,platform:'browser' as const,format:'iife' as const,minify:true,write:false as const};bundle=(await build({...options,entryPoints:[resolve(root,'packages/runtime/src/mermaid-bundle.ts')],plugins:[mermaidMathPlugin(root)]})).outputFiles[0]!.text;upstream=(await build({...options,stdin:{contents:"import mermaid from 'mermaid';globalThis.mermaidOriginal=mermaid;",resolveDir:root,sourcefile:'sankey-original.js'}})).outputFiles[0]!.text;});
const config=(outlined=false,showValues=false,align='justify',prefix='',suffix='')=>({startOnLoad:false,securityLevel:'strict',theme:'base',deterministicIds:true,themeVariables:{fontFamily:'Arial, sans-serif',fontSize:'14px'},sankey:{useMaxWidth:false,showValues,nodeAlignment:align,labelStyle:outlined?'outlined':'legacy',prefix,suffix}});

test('plain Sankey preserves upstream viewBox, native nodes, links, and text',async({page})=>{
 await page.setContent('<!doctype html><main id="rendered"></main>');await page.addScriptTag({content:bundle});await page.addScriptTag({content:upstream});
 const result=await page.evaluate(async({plain,config})=>{const host=document.querySelector('#rendered')!,summary=(text:string)=>{host.innerHTML=text;const svg=host.querySelector('svg')!;return {viewBox:svg.getAttribute('viewBox'),nodes:[...svg.querySelectorAll('.nodes rect')].map(n=>[n.getAttribute('x'),n.getAttribute('y'),n.getAttribute('width'),n.getAttribute('height'),n.parentElement?.getAttribute('transform')]),links:[...svg.querySelectorAll('.links path')].map(n=>[n.getAttribute('d'),n.getAttribute('stroke-width')]),text:[...svg.querySelectorAll('text')].map(n=>n.textContent),stage:svg.querySelectorAll('.vs-sankey-math').length};};const patched=(window as any).mermaid,original=(window as any).mermaidOriginal;patched.initialize(config);original.initialize(config);return {patched:summary((await patched.render('sankey-plain-patched',plain)).svg),original:summary((await original.render('sankey-plain-original',plain)).svg)};},{plain,config:config()});
 expect(result.patched).toEqual(result.original);expect(result.patched.stage).toBe(0);
});

test('math Sankey preserves native geometry while measuring labels at widths, styles, values, and alignments',async({page})=>{
 test.setTimeout(120_000);await page.setContent('<!doctype html><main id="rendered"></main>');await page.addScriptTag({content:bundle});await page.addScriptTag({content:upstream});
 for(const width of [320,1440])for(const outlined of [false,true])for(const showValues of [false,true])for(const align of ['justify','left','right','center'] as const)await test.step(`${width}/${outlined}/${showValues}/${align}`,async()=>{
  await page.setViewportSize({width,height:900});const result=await page.evaluate(async({math,config,id})=>{const host=document.querySelector('#rendered')!,patched=(window as any).mermaid,original=(window as any).mermaidOriginal;patched.initialize(config);original.initialize(config);host.innerHTML=(await patched.render(id,math)).svg;const svg=host.querySelector<SVGSVGElement>('svg')!,box=(n:Element)=>{const b=n.getBoundingClientRect();return {left:b.left,right:b.right,top:b.top,bottom:b.bottom};},labels=[...svg.querySelectorAll<SVGElement>('[data-vs-mermaid-label^="node:"]')].map(n=>({key:n.getAttribute('data-vs-mermaid-label'),box:box(n),math:n.querySelectorAll('math').length,backdrops:[...n.querySelectorAll(':scope > rect')].map(rect=>rect.getAttribute('fill')),ink:[...n.querySelectorAll('math,math *')].map(box).filter(b=>b.right>b.left&&b.bottom>b.top)}));const patchedGeometry={nodes:[...svg.querySelectorAll('.nodes rect')].map(n=>[n.getAttribute('x'),n.getAttribute('y'),n.getAttribute('width'),n.getAttribute('height'),n.parentElement?.getAttribute('transform')]),links:[...svg.querySelectorAll('.links path')].map(n=>[n.getAttribute('d'),n.getAttribute('stroke-width')])};const values=[...svg.querySelectorAll('[data-vs-sankey-value]')].map(n=>({text:n.textContent,math:n.querySelectorAll('math').length}));const leaders=[...svg.querySelectorAll('[data-vs-sankey-leader]')].map(n=>n.getAttribute('data-vs-sankey-leader'));const outer=box(svg);host.innerHTML=(await original.render(`${id}-original`,math)).svg;const originalGeometry={nodes:[...host.querySelectorAll('.nodes rect')].map(n=>[n.getAttribute('x'),n.getAttribute('y'),n.getAttribute('width'),n.getAttribute('height'),n.parentElement?.getAttribute('transform')]),links:[...host.querySelectorAll('.links path')].map(n=>[n.getAttribute('d'),n.getAttribute('stroke-width')])};return {outer,labels,values,leaders,patchedGeometry,originalGeometry,stage:svg.querySelectorAll('.vs-sankey-math').length,leaks:document.querySelectorAll('[data-vs-sankey-stage]').length};},{math,config:config(outlined,showValues,align),id:`sankey-${width}-${outlined}-${showValues}-${align}`});
  expect(result.stage).toBe(1);expect(result.leaks).toBe(0);expect(result.patchedGeometry).toEqual(result.originalGeometry);expect(result.labels.map(label=>label.key).sort()).toEqual(['node:0','node:1','node:2','node:3']);expect(result.labels.every(label=>label.math>0)).toBe(true);
  for(const label of result.labels){expect(label.box.left).toBeGreaterThanOrEqual(result.outer.left-1);expect(label.box.right).toBeLessThanOrEqual(result.outer.right+1);expect(label.box.top).toBeGreaterThanOrEqual(result.outer.top-1);expect(label.box.bottom).toBeLessThanOrEqual(result.outer.bottom+1);for(const ink of label.ink){expect(ink.left).toBeGreaterThanOrEqual(label.box.left-1);expect(ink.right).toBeLessThanOrEqual(label.box.right+1);expect(ink.top).toBeGreaterThanOrEqual(label.box.top-1);expect(ink.bottom).toBeLessThanOrEqual(label.box.bottom+1);}}for(let first=0;first<result.labels.length;first++)for(let second=first+1;second<result.labels.length;second++){const a=result.labels[first]!.box,b=result.labels[second]!.box;expect(a.right<=b.left||b.right<=a.left||a.bottom<=b.top||b.bottom<=a.top).toBe(true);}
  if(showValues){expect(result.values).toHaveLength(4);expect(result.values.every(value=>value.math===0)).toBe(true);}else expect(result.values).toEqual([]);expect(result.leaders.length).toBeGreaterThan(0);for(const label of result.labels){expect(label.backdrops).toHaveLength(outlined?1:0);if(outlined)expect(label.backdrops[0]).not.toBe('none');}
 });
});

test('generated value prefixes and suffixes remain literal text',async({page})=>{
 await page.setContent('<!doctype html><main id="rendered"></main>');await page.addScriptTag({content:bundle});const result=await page.evaluate(async({config})=>{const mermaid=(window as any).mermaid;mermaid.initialize(config);const host=document.querySelector('#rendered')!;host.innerHTML=(await mermaid.render('sankey-values',String.raw`sankey
"$$x$$",b,2
`)).svg;return {values:[...host.querySelectorAll('[data-vs-sankey-value]')].map(n=>({text:n.textContent,math:n.querySelectorAll('math').length})),labels:[...host.querySelectorAll('[data-vs-mermaid-label]')].map(n=>({key:n.getAttribute('data-vs-mermaid-label'),math:n.querySelectorAll('math').length}))};},{config:config(false,true,'justify','$$prefix$$','$$suffix$$')});expect(result.values).toEqual([{text:'$$prefix$$2$$suffix$$',math:0},{text:'$$prefix$$2$$suffix$$',math:0}]);expect(result.labels).toEqual([{key:'node:0',math:1},{key:'node:1',math:0}]);
});

test('retains native gradient definitions, link targets, and computed strokes with locally resolvable URLs',async({page})=>{
 await page.setContent('<!doctype html><main id="rendered"></main>');await page.addScriptTag({content:bundle});await page.addScriptTag({content:upstream});
 const result=await page.evaluate(async({math,config})=>{const host=document.querySelector('#rendered')!,shape=(svg:SVGSVGElement)=>{const normalize=(value:string|null)=>value?.replace(/url\(#.+?\)/g,'url(#ID)').replace(/(^|[^A-Za-z0-9_-])[A-Za-z][\w-]*-\d+(?=$|[^A-Za-z0-9_-])/g,'$1ID')??null;const gradients=[...svg.querySelectorAll('linearGradient')].map(node=>({attrs:[...node.attributes].filter(a=>a.name!=='id').map(a=>[a.name,normalize(a.value)]),stops:[...node.querySelectorAll('stop')].map(stop=>[stop.getAttribute('offset'),stop.getAttribute('stop-color'),stop.getAttribute('stop-opacity')])}));const links=[...svg.querySelectorAll<SVGPathElement>('.links path')].map(path=>({d:path.getAttribute('d'),stroke:normalize(path.getAttribute('stroke')),computed:getComputedStyle(path).stroke,refs:[...path.getAttribute('stroke')!.matchAll(/url\(#([^)]*)\)/g)].map(match=>match[1]),resolved:[...path.getAttribute('stroke')!.matchAll(/url\(#([^)]*)\)/g)].every(match=>Boolean(svg.querySelector(`#${CSS.escape(match[1]!)}`)))}));return {gradients,links};};const patched=(window as any).mermaid,original=(window as any).mermaidOriginal;patched.initialize(config);original.initialize(config);host.innerHTML=(await patched.render('sankey-gradient-patched',math)).svg;const mine=shape(host.querySelector('svg')!);host.innerHTML=(await original.render('sankey-gradient-original',math)).svg;return {mine,upstream:shape(host.querySelector('svg')!)};},{math,config:{...config(),sankey:{...config().sankey,linkColor:'gradient'}}});
 expect(result.mine.gradients).toEqual(result.upstream.gradients);expect(result.mine.links.map(link=>[link.d,link.stroke,link.computed])).toEqual(result.upstream.links.map(link=>[link.d,link.stroke,link.computed]));expect(result.mine.links.every(link=>link.resolved)).toBe(true);
});

test('retains a one-pixel zero-flow path while theme CSS overrides native strokes',async({page})=>{
 await page.setContent('<!doctype html><main id="rendered"></main>');await page.addScriptTag({content:bundle});const result=await page.evaluate(async({config})=>{const mermaid=(window as any).mermaid;mermaid.initialize(config);const host=document.querySelector('#rendered')!;host.innerHTML=(await mermaid.render('sankey-zero',String.raw`sankey
"$$x$$",a,0
a,b,2
`)).svg;const svg=host.querySelector('svg')!;return {links:[...svg.querySelectorAll<SVGPathElement>('.links path')].map(path=>({width:Number(path.getAttribute('stroke-width')),computed:getComputedStyle(path).stroke,computedWidth:getComputedStyle(path).strokeWidth})),nodes:[...svg.querySelectorAll<SVGRectElement>('.nodes rect')].map(rect=>({stroke:getComputedStyle(rect).stroke,width:getComputedStyle(rect).strokeWidth}))};},{config:{...config(),themeCSS:'.nodes rect { stroke: #102030; stroke-width: 6px; } .links path { stroke: #405060; stroke-width: 9px; }'}});
 expect(result.links[0]!.width).toBe(1);expect(result.links.every(link=>link.computed==='rgb(64, 80, 96)'&&link.computedWidth==='9px')).toBe(true);expect(result.nodes.every(node=>node.stroke==='rgb(16, 32, 48)'&&node.width==='6px')).toBe(true);
});

test('invalid Sankey math and geometry fail without a staged leak, then a later render recovers',async({page})=>{
 await page.setContent('<!doctype html><main id="rendered"></main>');await page.addScriptTag({content:bundle});const result=await page.evaluate(async({config})=>{const mermaid=(window as any).mermaid;mermaid.initialize(config);const failures=[] as boolean[];for(const [id,source] of [['bad','sankey\n"$$\\unknownSankey$$",b,1\n'],['cycle','sankey\n"$$x$$",b,1\nb,"$$x$$",1\n'],['zero','sankey\n"$$x$$",b,0\n']] as const){try{await mermaid.render(`sankey-${id}`,source);failures.push(false);}catch{failures.push(true);}}const leaks=document.querySelectorAll('[data-vs-sankey-stage]').length,host=document.querySelector('#rendered')!;host.innerHTML=(await mermaid.render('sankey-recovery','sankey\n"$$x$$",b,1\n')).svg;return {failures,leaks,stage:host.querySelectorAll('.vs-sankey-math').length,labels:[...host.querySelectorAll('[data-vs-mermaid-label]')].map(n=>n.getAttribute('data-vs-mermaid-label'))};},{config:config()});expect(result).toEqual({failures:[true,true,true],leaks:0,stage:1,labels:['node:0','node:1']});
});
