import { spawn } from 'node:child_process';
import { chromium } from '/home/r/Documents/MyStuff/random_ts/visser/node_modules/playwright/index.mjs';
const server = spawn(process.execPath, ['serve.mjs', '4611'], { stdio: 'ignore', cwd: '/home/r/Documents/MyStuff/random_ts/visser/spikes/mermaid' });
await new Promise((r) => setTimeout(r, 500));
const b = await chromium.launch();
const page = await b.newPage();
await page.goto('http://127.0.0.1:4611/inline/');
await page.waitForFunction(() => window.__done === true);
const seq = `sequenceDiagram\n autonumber\n participant U as User\n participant api as API\n U->>api: POST\n Note over U,api: note text\n loop retry\n  api-->>U: 503\n end\n api->>U: 200`;
const fc = `flowchart LR\n subgraph backend [Backend]\n  api[API] --> db[(Db)]\n end\n client --> backend`;
const st = `stateDiagram-v2\n [*] --> Active\n state Active {\n  [*] --> Running\n  Running --> Paused : pause\n }\n Active --> Done`;
const res = await page.evaluate(async ({ seq, fc, st }) => {
  const pick = (svg, sel, attrs) => { const d = document.createElement('div'); d.innerHTML = svg; return [...d.querySelectorAll(sel)].map((e) => attrs.map((a) => e.getAttribute(a)).join('|')); };
  const out = {};
  const s = (await window.mermaid.render('q1', seq)).svg;
  out.seqMessages = pick(s, '[data-et="message"]', ['data-id', 'data-from', 'data-to']);
  out.seqNotes = pick(s, '[data-et="note"], .note', ['data-id', 'class']).slice(0, 4);
  const f1 = (await window.mermaid.render('q2', fc)).svg;
  out.fcNodes = pick(f1, 'g.node', ['id']);
  out.fcClusters = pick(f1, 'g.cluster', ['id', 'data-id']);
  out.fcEdges = pick(f1, '[data-et="edge"]', ['data-id']);
  window.mermaid.initialize({ startOnLoad: false, securityLevel: 'strict', theme: 'forest', flowchart: { htmlLabels: false } });
  const f2 = (await window.mermaid.render('q2', fc)).svg;
  out.fcNodesAfterConfigChange = pick(f2, 'g.node', ['id']);
  const t = (await window.mermaid.render('q3', st)).svg;
  out.stateNodes = pick(t, 'g.node', ['id']);
  out.stateEdges = pick(t, '[data-et="edge"], path[data-id]', ['data-id']);
  return out;
}, { seq, fc, st });
console.log(JSON.stringify(res, null, 1));
await b.close(); server.kill();
