// Pinned Mermaid 12 Agentflow collector. Agentflow deliberately preserves
// comments while parsing, so it cannot share Flowchart's comment-stripping
// parser mapping or its grammar reduction contract.
import { MathPolicyError } from '../math/policy.ts';
import { mapMermaidFence } from './flowchart-source.ts';
import type { FlowchartLabelRecord, FlowchartShapeDataRecord, FlowchartLabels } from './flowchart-labels.ts';
import type { ProvenanceText } from './source-provenance.ts';

type Range=[number,number];
type Loc={range?:Range};
type Text={text:string;type?:string};
type Edge={id?:string;start:string;end:string;text:string;labelType?:string};
type Vertex={text?:string;labelType?:string};
type Graph={id:string;title:string;labelType?:string};
type Db={clear:()=>void;sanitizeText:(text:string)=>string;addVertex:(...args:unknown[])=>unknown;addLink:(start:string[],end:string[],type:{text?:Text})=>unknown;addSubGraph:(...args:unknown[])=>unknown;addConnector:(text?:Text,title?:Text)=>unknown;setAccTitle:(value:string)=>unknown;setAccDescription:(value:string)=>unknown;getVertices:()=>Map<string,Vertex>;getEdges:()=>Edge[];getSubGraphs:()=>Graph[];getConnectors:()=>Array<Vertex&{id:string}>};
type Parser={yy:Record<string,unknown>;lexer:{options:Record<string,unknown>;performAction:(...args:unknown[])=>unknown};performAction:(...args:unknown[])=>unknown;parse:(source:string)=>unknown;productions_:unknown[]};
type Pinned={Parser:new()=>Parser;lexer:Parser['lexer'];productions_:unknown[]};
type Module={diagram:{parser:{parser:Pinned};db:Db};visserAgentflowContract?:number};
type Context={production:number;values:unknown[];locations:Loc[];range:Range};

// Text reductions and DB-effect reductions are part of the native grammar
// contract. Pin both shape and selected productions rather than guessing from
// rendered SVG text.
const TEXT_REDUCTIONS=new Set([92,93,94,95,99,100,101,102,116,117,118,119]);
const PINNED:ReadonlyArray<readonly[number,number,number]>=[[38,7,9],[39,7,10],[40,7,6],[41,7,7],[42,7,4],[44,7,7],[45,7,8],[46,7,4],[47,7,5],[49,7,2],[50,7,2],[51,7,1],[56,34,2],[57,34,1],[58,21,4],[59,21,3],[60,21,4],[62,21,2],[65,45,6],[69,48,4],[85,48,1],[90,44,3],[91,44,4],[92,79,1],[93,79,2],[94,79,1],[95,79,1],[99,31,1],[100,31,2],[101,31,1],[102,31,1],[116,29,1],[117,29,2],[118,29,1],[119,29,1]];
function invalid(message:string):never{throw new MathPolicyError('E_MATH_INVALID',`agentflow grammar collector: ${message}`);}
function bytes(source:string):Array<number|undefined>{const result:Array<number|undefined>=Array(source.length+1);result[0]=0;for(let at=0;at<source.length;){const point=source.codePointAt(at)!;if(point>=0xd800&&point<=0xdfff)invalid('invalid source surrogate');const width=point>0xffff?2:1;result[at+width]=result[at]!+(point<0x80?1:point<0x800?2:point<0x10000?3:4);at+=width;}return result;}
function provenance(mapped:ProvenanceText,table:readonly(number|undefined)[],range:Range){const [start,end]=range;if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start<0||end<=start||end>mapped.length)invalid('invalid reduction range');const origin=mapped.mapRange(start,end);if(origin.synthetic||origin.intervals.length===0)invalid('missing source origin');const intervals=origin.intervals.map(({start,end})=>{const startByte=table[start],endByte=table[end];if(startByte===undefined||endByte===undefined)invalid('reduction splits Unicode point');return{start,end,startByte,endByte};});return{parserStart:start,parserEnd:end,intervals,synthetic:false};}
function trimmed(value:ProvenanceText){const start=value.text.length-value.text.trimStart().length;return value.slice(start,Math.max(start,value.text.trimEnd().length));}
function dbText(value:ProvenanceText){const clean=trimmed(value);return clean.text.startsWith('"')&&clean.text.endsWith('"')&&clean.length>=2?clean.slice(1,clean.length-1):clean;}
function mapAgentflowParserInput(original:string,rendered:string){let mapped=mapMermaidFence(original,rendered);const leading=mapped.text.length-mapped.text.trimStart().length;mapped=mapped.slice(leading,mapped.length);for(const pattern of [/style.*:\S*#.*;/g,/classDef.*:\S*#.*;/g])mapped=mapped.replaceRegex(pattern,(_match,span)=>span.slice(0,span.length-1));mapped=mapped.replaceRegex(/#\w+;/g,match=>{const inner=match[0].slice(1,-1);return /^\+?\d+$/.test(inner)?`\uFB02\u00B0\u00B0${inner}\u00B6\u00DF`:`\uFB02\u00B0${inner}\u00B6\u00DF`;});return mapped.replaceRegex(/}\s*\n/g,(_match,span)=>span.slice(0,1).concat(span.slice(span.length-1,span.length)));}

/** Collect grammar-owned Agentflow labels with original fence coordinates. */
export async function extractAgentflowLabels(originalSource:string,renderedSource=originalSource):Promise<FlowchartLabels>{
 let parserInput=mapAgentflowParserInput(originalSource,renderedSource);parserInput=parserInput.concat(parserInput.synthetic('\n'));
 const byteTable=bytes(originalSource);
 // @ts-expect-error Mermaid provides no declarations for its pinned parser chunk.
 const module=await import('mermaid/dist/chunks/mermaid.core/diagram-22UHCM2B.mjs') as Module;
 const pinned=module.diagram?.parser?.parser;
 if(module.visserAgentflowContract!==1||typeof pinned?.Parser!=='function'||!pinned.lexer||pinned.productions_?.length!==205||PINNED.some(([at,symbol,length])=>JSON.stringify(pinned.productions_[at])!==JSON.stringify([symbol,length])))invalid('pinned Agentflow reduction contract changed');
 const parser=new pinned.Parser();parser.lexer=Object.create(pinned.lexer) as Parser['lexer'];parser.lexer.options={...pinned.lexer.options,ranges:true};
 const db=module.diagram.db, records:FlowchartLabelRecord[]=[],shapeData:FlowchartShapeDataRecord[]=[];
 const textRanges=new WeakMap<object,Range>(),shapeRanges=new Map<string,{value:ProvenanceText;range:Range}>();let context:Context|undefined,effectIndex=0;const final=new Map<string,number>();
 const rangeKey=(location:Loc)=>location.range?`${location.range[0]}:${location.range[1]}`:invalid('location has no grammar range');
 const rangeFor=(text:Text)=>textRanges.get(text as object)??invalid('text object has no grammar range');
 const metadataValue=(metadata:string)=>{if(!context)invalid('metadata has no parser context');const found=context.locations.map(location=>shapeRanges.get(rangeKey(location))).filter((value):value is {value:ProvenanceText;range:Range}=>value!==undefined);if(found.length!==1||found[0]!.value.text!==metadata)invalid('metadata has no grammar-owned token provenance');return found[0]!;};
 const mapped=(range:Range,value:string)=>{const source=parserInput.slice(...range);return source.text===value?source:source.replace(0,source.length,value);};
 const addRecord=(record:FlowchartLabelRecord)=>{const prior=record.ownerId&&record.role.startsWith('node.')?final.get(record.ownerId):undefined;if(prior!==undefined)records[prior]!.active=false;if(record.ownerId&&record.role.startsWith('node.')&&record.assignsLabel)final.set(record.ownerId,records.length);records.push(record);};
 const originals={addVertex:db.addVertex,addLink:db.addLink,addSubGraph:db.addSubGraph,addConnector:db.addConnector,setAccTitle:db.setAccTitle,setAccDescription:db.setAccDescription,sanitizeText:db.sanitizeText};
 const makeNode=(role:'node.explicit'|'node.bare',id:string,text:Text,value:string,assignsLabel:boolean,current:number,labelType=text.type)=>{const range=rangeFor(text),mappedValue=dbText(mapped(range,text.text));if(mappedValue.text!==value)invalid('node label differs from fresh DB effect');addRecord({role,ownerId:id,semanticValue:value,mappedValue,labelType,assignsLabel,active:assignsLabel,effectIndex:current,provenance:provenance(parserInput,byteTable,range)});};
 try{
  db.clear();db.sanitizeText=text=>text;
  const lexerAction=parser.lexer.performAction;
  parser.lexer.performAction=function(this:{yytext:string;yylloc:Loc},...args:unknown[]){const rule=args[2] as number,raw=this.yytext,range=this.yylloc?.range,result=lexerAction.apply(this,args);if(result===43){if(!range)invalid('shapeData token has no range');const source=parserInput.slice(...range);let value=source;if(rule===7)value=source.slice(0,0);else if(rule===10)value=source.replaceRegex(/\n\s*/g,()=>'<br/>');if(source.text!==raw||value.text!==this.yytext)invalid('shapeData lexer transform changed');shapeRanges.set(`${range[0]}:${range[1]}`,{value,range});}return result;};
  db.addVertex=(...args:unknown[])=>{const id=args[0] as string,text=args[1] as Text|undefined,metadata=args[7] as string|undefined,previous=db.getVertices().get(id);const current=++effectIndex;const result=originals.addVertex(...args);const vertex=db.getVertices().get(id);if(text&&vertex?.text!==undefined)makeNode('node.explicit',id,text,vertex.text,true,current,vertex.labelType);else if(!text&&context?.production===85&&previous===undefined&&vertex?.text===id){const range=context.range,mappedValue=mapped(range,id);addRecord({role:'node.bare',ownerId:id,semanticValue:id,mappedValue,labelType:'text',assignsLabel:true,active:true,effectIndex:current,provenance:provenance(parserInput,byteTable,range)});}if(metadata!==undefined){if(typeof metadata!=='string')invalid('metadata is not text');const raw=metadataValue(metadata);const targetKind=db.getSubGraphs().some(graph=>graph.id===id)?'subgraph':db.getEdges().some(edge=>edge.id===id)?'edge':id==='connectors'||db.getConnectors().some(connector=>connector.id===id)?'connector':'node';shapeData.push({ownerId:id,targetKind,rawValue:metadata,mappedRawValue:raw.value,effectIndex:current,provenance:provenance(parserInput,byteTable,raw.range)});}return result;};
  db.addConnector=(id,title)=>{const ownerId=id?.text.trim(),previous=ownerId?db.getVertices().get(ownerId):undefined,current=++effectIndex;const result=originals.addConnector(id,title);if(!ownerId)return result;const vertex=db.getVertices().get(ownerId),authored=title?.text.trim()?title:previous===undefined?id:undefined;if(authored){if(vertex?.text===undefined)invalid('connector title had no DB effect');makeNode('node.explicit',ownerId,authored,vertex.text,true,current,vertex.labelType);}return result;};
  db.addLink=(start,end,type)=>{const before=db.getEdges().length,current=++effectIndex;const result=originals.addLink(start,end,type);if(type?.text){const added=db.getEdges().slice(before);if(added.length!==start.length*end.length||!added.length)invalid('edge label fanout differs from DB effect');const range=rangeFor(type.text),mappedValue=dbText(mapped(range,type.text.text));if(added.some(edge=>edge.text!==mappedValue.text))invalid('edge label differs from DB effect');records.push({role:'edge',semanticValue:mappedValue.text,mappedValue,labelType:added[0]!.labelType,edgeIndices:added.map((_,index)=>before+index),edgeIds:added.map(edge=>edge.id??''),endpoints:added.map(edge=>({start:edge.start,end:edge.end})),assignsLabel:true,active:true,effectIndex:current,provenance:provenance(parserInput,byteTable,range)});}return result;};
  db.addSubGraph=(...args:unknown[])=>{const id=args[0] as Text|undefined,title=args[2] as Text|undefined,before=id?.text?db.getSubGraphs().find(graph=>graph.id===id.text.trim()):undefined,current=++effectIndex;const result=originals.addSubGraph(...args);const graph=db.getSubGraphs().find(candidate=>candidate.id===result);if(!graph)invalid('flow declaration had no DB effect');const authored=title?.text?title:before===undefined?id:undefined;if(authored){const range=rangeFor(authored),mappedValue=title?.text?trimmed(mapped(range,title.text)):mapped(range,authored.text).replace(0,authored.text.length,'');if(mappedValue.text!==graph.title)invalid('flow title differs from DB effect');const key=`subgraph:${graph.id}`,prior=final.get(key);if(prior!==undefined)records[prior]!.active=false;final.set(key,records.length);records.push({role:'subgraph',ownerId:graph.id,semanticValue:graph.title,mappedValue,labelType:graph.labelType,assignsLabel:true,active:true,effectIndex:current,provenance:provenance(parserInput,byteTable,range)});}else if(before===undefined){const range=context?.range;if(!range)invalid('anonymous flow has no grammar range');const mappedValue=mapped(range,parserInput.slice(...range).text).replace(0,range[1]-range[0],'');const key=`subgraph:${graph.id}`;final.set(key,records.length);records.push({role:'subgraph',ownerId:graph.id,semanticValue:graph.title,mappedValue,labelType:graph.labelType,assignsLabel:true,active:true,effectIndex:current,provenance:provenance(parserInput,byteTable,range)});}return result;};
  const accessibility=(role:'accTitle'|'accDescr',value:string)=>{const current=++effectIndex,range=context?.locations.at(-1)?.range,token=context?.values.at(-1);if(!range||typeof token!=='string')invalid(`${role} has no grammar range`);const mappedValue=trimmed(mapped(range,token));if(mappedValue.text!==value)invalid(`${role} differs from DB effect`);const prior=final.get(role);if(prior!==undefined)records[prior]!.active=false;final.set(role,records.length);records.push({role,semanticValue:value,mappedValue,assignsLabel:true,active:true,effectIndex:current,provenance:provenance(parserInput,byteTable,range)});};
  db.setAccTitle=value=>accessibility('accTitle',value);db.setAccDescription=value=>accessibility('accDescr',value);
  parser.yy=db as unknown as Record<string,unknown>;const action=parser.performAction;parser.performAction=function(this:{ $?:unknown;_$?:Loc},...args:unknown[]){const production=args[4] as number,stackValues=args[5] as unknown[],stackLocations=args[6] as Loc[],range=this._$?.range;if(!range)invalid('parser did not emit reduction ranges');const length=(pinned.productions_[production] as [number,number])[1],values=length?stackValues.slice(-length):[],locations=length?stackLocations.slice(-length):[],prior=context;context={production,values,locations,range};try{const result=action.apply(this,args);if(TEXT_REDUCTIONS.has(production)&&this.$&&typeof this.$==='object'&&typeof (this.$ as Text).text==='string')textRanges.set(this.$ as object,range);if((production===56||production===57)&&this._$){const parts=locations.map(location=>shapeRanges.get(rangeKey(location))).filter((value):value is {value:ProvenanceText;range:Range}=>value!==undefined);if(!parts.length||typeof this.$!=='string')invalid('shapeData reduction provenance changed');const value=parserInput.slice(0,0).concatAll(parts.map(part=>part.value));if(value.text!==this.$)invalid('shapeData reduction changed');shapeRanges.set(`${range[0]}:${range[1]}`,{value,range});}return result;}finally{context=prior;}};
  parser.parse(parserInput.text);
 }finally{db.addVertex=originals.addVertex;db.addLink=originals.addLink;db.addSubGraph=originals.addSubGraph;db.addConnector=originals.addConnector;db.setAccTitle=originals.setAccTitle;db.setAccDescription=originals.setAccDescription;db.sanitizeText=originals.sanitizeText;db.clear();}
 records.sort((a,b)=>a.provenance.intervals[0]!.start-b.provenance.intervals[0]!.start);shapeData.sort((a,b)=>a.provenance.intervals[0]!.start-b.provenance.intervals[0]!.start);
 return{records,shapeData,parserSource:parserInput.text};
}
