import {mkdtempSync,readFileSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';import {join} from 'node:path';import {expect,it} from 'vitest';
// @ts-expect-error test harness dependency.
import {JSDOM} from 'jsdom';
import {loadBundle} from '../../packages/core/src/model/bundle.ts';import {compileDocument} from '../../packages/core/src/compiler/compile.ts';
const frontmatter=readFileSync(new URL('../../examples/bounded-queue/index.md',import.meta.url),'utf8').split('---')[1];
async function compiled(source:string){const dir=mkdtempSync(join(tmpdir(),'visser-info-public-'));try{writeFileSync(join(dir,'index.md'),`---${frontmatter}---\n\n{% mermaid id="figure" title="Info" question="What changed?" %}\n\n\`\`\`mermaid\n${source}\`\`\`\n{% /mermaid %}\n`);const bundle=loadBundle(join(dir,'index.md'));expect(bundle.diagnostics.filter(d=>d.severity==='error')).toEqual([]);const output=await compileDocument(bundle,{version:'0.0.0',sha256:'a'.repeat(64),integrity:{'mermaid.js':'sha384-TESTDIGEST'}},{audience:'private',includeSource:false,layoutFallback:false});return {bundle,doc:new JSDOM(new TextDecoder().decode(output.files.find(file=>file.path.endsWith('/index.html'))!.bytes)).window.document};}finally{rmSync(dir,{recursive:true,force:true});}}
it('validates hidden Info records without claiming visible source owners',async()=>{const source='info\ntitle $$hiddenold$$\ntitle $$hiddennew$$\naccTitle: $$access$$\naccDescr: plain\n';const {bundle,doc}=await compiled(source),figure:any=bundle.model.mermaid.get('figure'),element=doc.querySelector('#x-figure')!;expect(figure.infoMath.total.occurrences).toBe(3);expect(element.hasAttribute('data-vs-mermaid-math')).toBe(true);expect(JSON.parse(element.getAttribute('data-vs-mermaid-source-map')!)).toMatchObject({format:'info',labels:[]});expect(element.textContent).toContain('title $$hiddenold$$');});
it('rejects invalid overwritten Info math',async()=>{await expect(compiled('info\ntitle $$\\href{x}{bad}$$\ntitle plain\n')).rejects.toThrow();});
